### ISSUE TITLE
TypeError: unsupported format string passed to Tensor.__format__

### ISSUE THREAD

**Issue by aisosalo** [MIPT-Oulu/Collagen#69]
When running a segmentation pipeline `TypeError` is issued during evaluation stage.

Class and method potentially connected to the issue:
```python
class ItemWiseBinaryJaccardDiceMeter(Meter):

    ...

    @staticmethod
    def compute_dice(target, output, eps=1e-8):
        if target.sum() == 0 and output.sum() == 0:
            return torch.tensor(1)
        num = output.size(0)
        m1 = output.view(num, -1).float()
        m2 = target.view(num, -1).float()

        a = (m1 * m2).sum(1).add(eps)
        b = (m1.sum(1) + m2.sum(1)).add(eps)

        result = a.mul(2).div(b)

        return result
```

Validation callback from the training script in question:
```python
val_cbs = (RunningAverageMeter(prefix="eval",
                                name="loss"),
                 ItemWiseBinaryJaccardDiceMeter(prefix="eval/all",
                                                  name='dice',
                                                  parse_output=lambda x: torch.sigmoid(x).gt(0.3).squeeze().float(),
                                                  parse_target=lambda x: x.squeeze().to(device)),
                 SimpleLRScheduler('eval/loss', ReduceLROnPlateau(optimizer=optimizer,
                                                   patience=5,
                                                   factor=0.1,
                                                   eps=1e-9)),
                 ScalarMeterLogger(writer=summary_writer[fold_id],
                                                  comment='validation',
                                                  log_dir=str(logs_dir / 'fold_{}'.format(fold_id) / snapshot_name)),
                 ModelSaver(metric_names='eval/loss',
                              prefix=f'fold_{fold_id}',
                              save_dir=str(snapshots_dir / snapshot_name),
                              conditions='min',
                              model=model)
)
```

Traceback:
```
Traceback (most recent call last):
  File "/home/myusername/Downloads/pycharm-anaconda-2020.1/plugins/python/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/myusername/Downloads/pycharm-anaconda-2020.1/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/myusername/PycharmProjectFiles/Test/run_training.py", line 189, in <module>
    strategy.run()
  File "/mnt/myusername/PycharmProjectFiles/Collagen/collagen/strategies/_strategy.py", line 282, in run
    n_batches=self.__num_batches_by_stage[stage])
  File "/mnt/myusername/PycharmProjectFiles/Collagen/collagen/strategies/_strategy.py", line 190, in _call_callbacks_by_name
    getattr(cb, cb_func_name)(strategy=self, **kwargs)
  File "/mnt/myusername/PycharmProjectFiles/Collagen/collagen/callbacks/logging/loggers.py", line 184, in on_batch_end
    postfix_progress[cb.desc] = self.__format_metric(cb_cur)
  File "/mnt/myusername/PycharmProjectFiles/Collagen/collagen/callbacks/logging/loggers.py", line 154, in _default_format_metric
    return f"{x:.03f}"
  File "/home/myusername/anaconda3/envs/py37_env/lib/python3.7/site-packages/torch/tensor.py", line 341, in __format__
    return object.__format__(self, format_spec)
TypeError: unsupported format string passed to Tensor.__format__
```

Collagen version 0.0.1 according to this [setup.py](https://github.com/MIPT-Oulu/Collagen/blob/0c65efcc47837b4c10959572b3b9af2be0511003/setup.py#L45) file (`master` branch).

System:
```python
import platform, sys, torch
print(platform.platform(),
            "\nPython", sys.version,
            "\nPyTorch", torch.__version__)

Linux-5.3.0-51-generic-x86_64-with-debian-buster-sid 
Python 3.7.7 (default, Mar 26 2020, 15:48:22) 
[GCC 7.3.0] 
PyTorch 1.2.0
```

**Comment by hoanghng** [comment]
Hi @aisosalo ,

The `logger` expects the output of your meter to be scalar, not pytorch tensor. You can use the supported function `to_cpu` without `use_numpy` to convert your result to scalar.

**Comment by aisosalo** [comment]
With batch size `32` the `target` and `output` for function `compute_dice` (ItemWiseBinaryJaccardDiceMeter) are of the following form:
```python
tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 1., 0.],
         [0., 0., 0.,  ..., 1., 1., 0.],
         [0., 0., 0.,  ..., 1., 0., 0.]],
        [[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 1., 1., 1.]],
        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.]],
        ...,
        [[1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 1., 1., 1.]],
        [[0., 0., 0.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 1., 0.],
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 1., 1., 1.]],
        [[1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         [1., 1., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 1., 1., 1.],
         [0., 0., 0.,  ..., 1., 1., 1.]]], device='cuda:0')
```

and the `result` after the the function (`result.shape` gives `32`)
```python
tensor([0.0059, 0.0039, 0.0029, 0.0034, 0.0177, 0.0061, 0.0095, 0.0147, 0.0208,
        0.0008, 0.0070, 0.0036, 0.0036, 0.0036, 0.0056, 0.0056, 0.0056, 0.0056,
        0.0056, 0.0051, 0.0051, 0.0051, 0.0035, 0.0035, 0.0035, 0.0055, 0.0535,
        0.0167, 0.0169, 0.0105, 0.0116, 0.0084], device='cuda:0')
```

Perhaps an additional fix to can be suggested?
